import random
# Data for korean dramas
korean_dramas = {
"Goblin": {"genre": "fantasy", "director": "Lee Eung Bok"},
"Descendants of the Sun": {"genre": "romance", "director": "Lee Eung Bok"},
" Crash Landing on You": {"genre": "romance", "director": "Lee Jung Hyo"},
" My Love from the Star": {"genre": "romance", "director": "Jang Tae Yoo"},
 "it's Okay to Not Be Okay": {"genre": "romance", "director": "Park Shin Woo"},
 "Hotel Del Luna": {"genre": "fantasy", "director": "Oh Choong Hwan"},
 "The Heirs": {"genre": "romance", "director": "Kang Shin Hyo"},
 "Reply 1988": {"genre": "romance", "director": "Shin Won Ho"},
 "Boys Over Flowers": {"genre": "romance", "director": "Jeon Ki Sang"},
 "What's Wrong with Secretary Kim": {"genre": "romance", "director": "Park Joon Hwa"},
"Strong Woman Do Bong Soon": {"genre": "romance", "director": "Lee Hyung Min"},
"Weightlifting Fairy Kim Bok Joo": {"genre": "romance", "director": "Oh Hyun Jong"},
 "Love Alarm": {"genre": "romance", "director": "Lee Na Jung"},
 "Moon Lovers": {"genre": "historical", "director": "Kim Kyu Tae"},
 "W": {"genre": "fantasy", "director": "Jung Dae Yoon"},
" Secret Garden": {"genre": "romance", "director": "Shin Woo Chul"},
 "The King: Eternal Monarch": {"genre": "fantasy", "director": "Baek Sang Hoon"},
 "Pinocchio": {"genre": "romance", "director": "Jo Soo Won"},
 "Signal": {"genre": "crime", "director": "Kim Won Suk"},
" While You Were Sleeping": {"genre": "fantasy", "director": "Oh Choong Hwan"},
  "The Master's Sun": {"genre": "horror", "director": "Jin Hyuk"},
 "Cheese in the Trap": {"genre": "romance", "director": "Lee Yoon Jung"},
 "Doctor Stranger": {"genre": "romance", "director": "Jin Hyuk"},
 "Oh My Ghost": {"genre": "romance", "director": "Yoo Je Won"},
 "Legend of the Blue Sea": {"genre": "romance", "director": "Jin Hyuk"},
 "Healer": {"genre": "action", "director": "Lee Jung Sub"},
 "Mr. Sunshine": {"genre": "historical", "director": "Lee Eung Bok"},
 "Tempted": {"genre": "romance", "director": "Kang In"},
"Itaewon Class": {"genre": "drama", "director": "Kim Sung Yoon"},
 "It's Okay, That's Love": {"genre": "romance", "director": "Kim Kyu Tae"},
"City Hunter": {"genre": "action", "director": "Jin Hyuk"},
 "Reply 1997": {"genre": "romance", "director": "Shin Won Ho"},
 "The Moon Embracing the Sun": {"genre": "historical", "director": "Kim Do Hoon"},
 "Vagabond": {"genre": "action", "director": "Yoo In Shik"},
 "Goblin": {"genre": "fantasy", "director": "Lee Eung Bok"},
 "Hwarang": {"genre": "historical", "director": "Yoon Sung Sik"},
 "Moonlight Drawn by Clouds": {"genre": "historical", "director": "Kim Sung Yoon"},
 "Fight for My Way": {"genre": "romance", "director": "Lee Na Jung"},
 "Scarlet Heart: Ryeo": {"genre": "historical", "director": "Kim Kyu Tae"},
 "Kill Me, Heal Me": {"genre": "romance", "director": "Kim Jin Man"},
"Doctor Romantic": {"genre": "medical", "director": "Yoo In Shik"},
 "My ID is Gangnam Beauty": {"genre": "romance", "director": "Choi Sung Bum"},
 "Fated to Love You": {"genre": "romance", "director": "Lee Dong Yoon"},
 "Abyss": {"genre": "fantasy", "director": "Yoo Je Won"},
 "100 Days My Prince": {"genre": "historical", "director": "Lee Jong Jae"},
 "Angel's Last Mission":  {"genre": "romance", "director": "Lee Jung Sub"},
 "The Beauty Inside": {"genre": "romance", "director": "Song Hyun Wook"},
 "Gu Family Book": {"genre": "fantasy", "director": "Shin Woo Chul"},
 "Prison Playbook": {"genre": "drama", "director": "Shin Won Ho"},
 "Come and Hug Me": {"genre": "romance", "director": "Choi Joon Bae"},
 "The Legend of the Blue Sea": {"genre": "romance", "director": "Jin Hyuk"},
 "The Secret Life of My Secretary": {"genre": "romance", "director": "Lee Gwang Young"},
 "Queen In Hyun's Man": {"genre": "romance", "director": "Kim Byung Soo"},
 "What's Wrong With Secretary Kim": {"genre": "romance", "director": "Park Joon Hwa"},
 "Flower of Evil": {"genre": "thriller", "director": "Kim Cheol Kyu"},
 "The Smile Has Left Your Eyes": {"genre": "thriller", "director": "Yoo Je Won"},
 "Her Private Life": {"genre": "romance", "director": "Hong Jong Chan"},
 "Personal Taste": {"genre": "romance", "director": "Son Hyung Suk"},
 "Love in the Moonlight": {"genre": "historical", "director": "Kim Sung Yoon"},
 "Heartstrings": {"genre": "romance", "director": "Pyo Min Soo"},
 "Hospital Playlist": {"genre": "medical", "director": "Shin Won Ho"},
 "Marriage, Not Dating": {"genre": "romance", "director": "Song Hyun Wook"},
"You're Beautiful": {"genre": "romance", "director": "Hong Sung Chang"},
 "Coffee Prince": {"genre": "romance", "director": "Lee Yoon Jung"},
 "My Girlfriend is a Gumiho": {"genre": "romance", "director": "Bu Seong Cheol"},
 "Cinderella and Four Knights": {"genre": "romance", "director": "Kwon Hyuk Chan"},
 "Rooftop Prince": {"genre": "historical", "director": "Shin Yoon Sub"},
 "The K2": {"genre": "action", "director": "Kwak Jung Hwan"},
 "My Mister": {"genre": "drama", "director": "Kim Won Suk"},
 "City Hall": {"genre": "romance", "director": "Shin Woo Chul"},
 "School 2013": {"genre": "drama", "director": "Lee Min Hong"},
 "Queen Seondeok": {"genre": "historical", "director": "Park Hong Kyun"},
 "The Greatest Love": {"genre": "romance", "director": "Park Hong Kyun"},
 "My Princess": {"genre": "romance", "director": "Kwon Seok Jang"},
 "Secret Garden": {"genre": "romance", "director": "Shin Woo Chul"},
 "City Hunter": {"genre": "action", "director": "Jin Hyuk"},
 "Boys Over Flowers": {"genre": "romance", "director": "Jeon Ki Sang"},
 "Full House": {"genre": "romance", "director": "Pyo Min Soo"},
 "Pasta": {"genre": "romance", "director": "Kwon Suk Jang"},
 "My Lovely Sam Soon": {"genre": "romance", "director": "Kim Yoon Chul"},
  "Stairway to Heaven": {"genre": "romance", "director": "Lee Jang Soo"},
 "Winter Sonata": {"genre": "romance", "director": "Yoon Seok Ho"},
 "Autumn in My Heart": {"genre": "romance", "director": "Yoon Seok Ho"},
 "That Winter, the Wind Blows": {"genre": "romance", "director": "Kim Kyu Tae"},
 "Love Rain": {"genre": "romance", "director": "Yoon Seok Ho"},
 "Secret Garden": {"genre": "romance", "director": "Shin Woo Chul"},
 "Coffee Prince": {"genre": "romance", "director": "Lee Yoon Jung"},
 "Oh My Venus": {"genre": "romance", "director": "Kim Hyung Suk"},
 "Boys Over Flowers": {"genre": "romance", "director": "Jeon Ki Sang"},
 "You're Beautiful": {"genre": "romance", "director": "Hong Sung Chang"},
 "Love in the Moonlight": {"genre": "historical", "director": "Kim Sung Yoon"},
 "Moon Lovers": {"genre": "historical", "director": "Kim Kyu Tae"},
 "Pinocchio": {"genre": "romance", "director": "Jo Soo Won"},
 "Heirs": {"genre": "romance", "director": "Kang Shin Hyo"},
 "Legend of the Blue Sea": {"genre": "romance", "director": "Jin Hyuk"},
 "Weightlifting Fairy Kim Bok Joo": {"genre": "romance", "director": "Oh Hyun Jong"},
 "Strong Woman Do Bong Soon": {"genre": "romance", "director": "Lee Hyung Min"},
 "Descendants of the Sun": {"genre": "romance", "director": "Lee Eung Bok"},
 "Goblin": {"genre": "fantasy", "director": "Lee Eung Bok"},
 "The King": {"genre": "fantasy", "director": "Baek Sang Hoon"},
}

#data for chinese drama
chinese_dramas = {
 "Go Ahead": {"genre": "romance", "director": "Ding Zi Guang"},
 "Eternal Love": {"genre": "fantasy", "director": "Lin Yufen"},
 "Love O2O": {"genre": "romance", "director": "Liu Shuailiang"},
 "The Untamed": {"genre": "fantasy", "director": "Zheng Weiwen"},
 "Ashes of Love": {"genre": "fantasy", "director": "Chu Rui Bin"},
 "Meteor Garden": {"genre": "romance", "director": "Zhang Jia Li"},
 "The Legend of Hao Lan": {"genre": "historical", "director": "Li Dachao"},
 "The Story of Minglan": {"genre": "historical", "director": "Zhang Kaizhou"},
 "Love and Destiny": {"genre": "fantasy", "director": "Lin Yufen"},
 "Princess Agents": {"genre": "historical", "director": "Wu Jinyuan"},
 "Nirvana in Fire": {"genre": "historical", "director": "Kong Sheng"},
 "Scarlet Heart": {"genre": "historical", "director": "Wu Jin Yuan"},
 "The King's Woman": {"genre": "historical", "director": "Li Huizhu"},
 "Goodbye My Princess": {"genre": "historical", "director": "Li Muge"},
 "Love is Sweet": {"genre": "romance", "director": "Yu Zhong Zhong"},
 "The Romance of Tiger and Rose": {"genre": "romance", "director": "Cha Chuan Yi"},
 "Well-Intended Love": {"genre": "romance", "director": "Wu Qiang"},
 "Joy of Life": {"genre": "historical", "director": "Sun Hao"},
 "My Sunshine": {"genre": "romance", "director": "Liu Jun Jie"},
 "My Little Princess": {"genre": "romance", "director": "Zhou Xiao Peng"},
"Arsenal Military Academy": {"genre": "romance", "director": "Chen Jin"},
 "Love Designer": {"genre": "romance", "director": "Shi Lei"},
 "Skate Into Love": {"genre": "romance", "director": "Zhou Xiaopeng"},
 "Find Yourself": {"genre": "romance", "director": "Ding Yingzhou"},
 "Put Your Head on My Shoulder": {"genre": "romance", "director": "Zhu Dong Ning"},
 "Love The Way You Are": {"genre": "romance", "director": "Zhou Xiao Peng"},
"A Love So Beautiful": {"genre": "romance", "director": "Yang Long"},
 "The King's Avatar": {"genre": "action", "director": "Lin Ke"},
 "Le Coup de Foudre": {"genre": "romance", "director": "Zhou Xiao Peng"},
 "My Girlfriend is an Alien": {"genre": "romance", "director": "Wang Xin"},
 "The Legends": {"genre": "fantasy", "director": "Li Shu"},
 "When We Were Young": {"genre": "romance", "director": "Zhang Lichuan"},
 "My Amazing Boyfriend": {"genre": "romance", "director": "Shen Yan"},
 "The Love Equations": {"genre": "romance", "director": "Lin Yufen"},
 "The Flame's Daughter": {"genre": "historical", "director": "Liang Shengquan"},
 "Boss & Me": {"genre": "romance", "director": "Zhao Baogang"},
 "The Eternal Love": {"genre": "romance", "director": "Liang Shengquan"},
 "Love Me If You Dare": {"genre": "crime", "director": "Yang Xuan"},
 "The Princess Weiyoung": {"genre": "historical", "director": "Liang Shengquan"},
 "Youth": {"genre": "romance", "director": "Li Xue"},
 "The Rise of Phoenixes": {"genre": "historical", "director": "Shen Yan"},
 "Accidentally in Love": {"genre": "romance", "director": "Qiu Zhong Wei"},
 "My Little Happiness": {"genre": "romance", "director": "Zhou Junjie"},
 "The Pillow Book": {"genre": "fantasy", "director": "Liu Chu Tian"},
 "My Huckleberry Friends": {"genre": "romance", "director": "Li Xiaohong"},
 "The Mystic Nine": {"genre": "mystery", "director": "Liang Shengquan"},
 "My Love, Enlighten Me": {"genre": "romance", "director": "Wu Qiang"},
 "Le Coup de Foudre": {"genre": "romance", "director": "Zhou Xiao Peng"},
 "The Journey of Flower": {"genre": "fantasy", "director": "Lin Yufen"},
 "My Robot Boyfriend": {"genre": "romance", "director": "Zhou Junjie"},
 "Novoland":{"genre": "fantasy", "director": "Yang Lei"},
 "The Brightest Star in the Sky": {"genre": "romance", "director": "Zhang Lichuan"},
 "The Legends of Monkey King": {"genre": "fantasy", "director": "Zhao Xiaoding"},
 "My Amazing Bride": {"genre": "romance", "director": "Yu Zhong Zhong"},
 "Love of Aurora": {"genre": "romance", "director": "Liang Shengquan"},
 "Memory Lost": {"genre": "mystery", "director": "Li Xiaohong"},
 "Love a Lifetime": {"genre": "romance", "director": "Wu Jinyuan"},
 "All I Want for Love is You": {"genre": "romance", "director": "Liu Han"},
 "Love in Time": {"genre": "romance", "director": "Lin Jianlong"},
 "Well-Intended Love 2": {"genre": "romance", "director": "Wu Qiang"},
 "The King of Blaze": {"genre": "fantasy", "director": "Lin Yufen"},
 "Master Devil Do Not Kiss Me": {"genre": "romance", "director": "Shen Wang"},
 "Love Better Than Immortality": {"genre": "fantasy", "director": "Lin Yufen"},
 "The Evolution of Our Love": {"genre": "romance", "director": "Wu Jian Xin"},
 "Skate Into Love": {"genre": "romance", "director": "Zhou Xiaopeng"},
 "The Journey Across the Night": {"genre": "romance", "director": "Liu Jin"},


}
#data for food items
food_items={

 "Apple Rabadi": {"type":"dessert","veg/nonveg":"veg"},
 "Chicken Curry": {"type":"main course","veg/nonveg":"nonveg"},
 "Vegetable Biryani": {"type":"main course","veg/nonveg":"veg"},
 "Tiramisu": {"type":"dessert","veg/nonveg":"veg"},
 "Sushi": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Paneer Tikka": {"type":"appetizer","veg/nonveg":"veg"},
 "Beef Stroganoff": {"type":"main course","veg/nonveg":"nonveg"},
 "Chocolate Fondue": {"type":"dessert","veg/nonveg":"veg"},
 "Caesar Salad": {"type":"appetizer","veg/nonveg":"veg"},
 "Fish Tacos": {"type":"main course","veg/nonveg":"nonveg"},
 "Mango Lassi": {"type":"beverage","veg/nonveg":"veg"},
 "Caprese Salad": {"type":"appetizer","veg/nonveg":"veg"},
 "Margherita Pizza": {"type":"main course","veg/nonveg":"veg"},
 "Chicken Wings": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Pad Thai": {"type":"main course","veg/nonveg":"nonveg"},
 "Apple Pie": {"type":"dessert","veg/nonveg":"veg"},
 "Gazpacho": {"type":"soup","veg/nonveg":"veg"},
  "Lobster Bisque": {"type":"soup","veg/nonveg":"nonveg"},
 "Beef Wellington": {"type":"main course","veg/nonveg":"nonveg"},
 "Greek Salad": {"type":"appetizer","veg/nonveg":"veg"},
 "Spaghetti Carbonara": {"type":"main course","veg/nonveg":"nonveg"},
 "Chicken Caesar Wrap": {"type":"main course","veg/nonveg":"nonveg"},
 "French Onion Soup": {"type":"soup","veg/nonveg":"veg"},
 "Peking Duck": {"type":"main course","veg/nonveg":"nonveg"},
 "Chocolate Mousse": {"type":"dessert","veg/nonveg":"veg"},
 "falafel": {"type":"appetizer","veg/nonveg":"veg"},
 "Beef Tacos": {"type":"main course","veg/nonveg":"nonveg"},
 "Veggie Burger": {"type":"main course","veg/nonveg":"veg"},
 "Chicken Satay": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Clam Chowder": {"type":"soup","veg/nonveg":"nonveg"},
 "Eggplant Parmesan": {"type":"main course","veg/nonveg":"veg"},
 "Philly Cheesesteak": {"type":"main course","veg/nonveg":"nonveg"},
 "Tandoori Chicken": {"type":"main course","veg/nonveg":"nonveg"},
 "Caesar Wrap": {"type":"main course","veg/nonveg":"nonveg"},
 "Ratatouille": {"type":"main course","veg/nonveg":"veg"},
 "Key Lime Pie": {"type":"dessert","veg/nonveg":"veg"},
 "Shrimp Scampi": {"type":"main course","veg/nonveg":"nonveg"},
 "Chicken Noodle Soup": {"type":"soup","veg/nonveg":"nonveg"},
 "Beef Teriyaki": {"type":"main course","veg/nonveg":"nonveg"},
 "Margarita": {"type":"beverage","veg/nonveg":"nonveg"},
 "Croissant": {"type":"pastry","veg/nonveg":"veg"},
 "Chicken Parmesan": {"type":"main course","veg/nonveg":"nonveg"},
 "Chocolate Chip Cookies": {"type":"dessert","veg/nonveg":"veg"},
 "Cucumber Salad": {"type":"appetizer","veg/nonveg":"veg"},
 "Beef Empanadas": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Lobster Roll": {"type":"main course","veg/nonveg":"nonveg"},
 "Mushroom Risotto": {"type":"main course","veg/nonveg":"veg"},
 "Spring Rolls": {"type":"appetizer","veg/nonveg":"veg"},
 "Chicken Alfredo": {"type":"main course","veg/nonveg":"nonveg"},
 "Margherita Salad": {"type":"appetizer","veg/nonveg":"veg"},
 "Pecan Pie": {"type":"dessert","veg/nonveg":"veg"},
 "Chicken Shawarma": {"type":"main course","veg/nonveg":"nonveg"},
 "French Fries": {"type":"side dish","veg/nonveg":"veg"},
 "Chicken Pot Pie": {"type":"main course","veg/nonveg":"nonveg"},
 "Paella": {"type":"main course","veg/nonveg":"nonveg"},
  "Tuna Salad": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Beef Bulgogi": {"type":"main course","veg/nonveg":"nonveg"},
 "Strawberry Shortcake": {"type":"dessert","veg/nonveg":"veg"},
 "Potato Soup": {"type":"soup","veg/nonveg":"veg"},
 "Pesto Pasta": {"type":"main course","veg/nonveg":"veg"},
 "Chicken Korma": {"type":"main course","veg/nonveg":"nonveg"},
 "Baklava": {"type":"dessert","veg/nonveg":"veg"},
 "Pulled Pork Sandwich": {"type":"main course","veg/nonveg":"nonveg"},
 "Cheese Platter": {"type":"appetizer","veg/nonveg":"veg"},
 "Beef Rendang": {"type":"main course","veg/nonveg":"nonveg"},
 "Garlic Bread": {"type":"side dish","veg/nonveg":"veg"},
 "Chicken Enchiladas": {"type":"main course","veg/nonveg":"nonveg"},
 "Fruit Salad": {"type":"appetizer","veg/nonveg":"veg"},
 "Clam Linguine": {"type":"main course","veg/nonveg":"nonveg"},
 "Creme Brulee": {"type":"dessert","veg/nonveg":"veg"},
 "Beef Gyro": {"type":"main course","veg/nonveg":"nonveg"},
 "Pancakes": {"type":"breakfast","veg/nonveg":"veg"},
 "Tofu Stir-Fry": {"type":"main course","veg/nonveg":"veg"},
 "Lobster Thermidor": {"type":"main course","veg/nonveg":"nonveg"},
 "Mango Sticky Rice": {"type":"dessert","veg/nonveg":"veg"},
 "Spinach and Feta Pie": {"type":"main course","veg/nonveg":"veg"},
 "Chicken Fajitas": {"type":"main course","veg/nonveg":"nonveg"},
 "Garlic Shrimp": {"type":"main course","veg/nonveg":"nonveg"},
 "Cannoli": {"type":"dessert","veg/nonveg":"veg"},
 "Veggie Spring Rolls": {"type":"appetizer","veg/nonveg":"veg"},
 "Beef Pho": {"type":"soup","veg/nonveg":"nonveg"},
 "Margherita Flatbread": {"type":"main course","veg/nonveg":"veg"},
 "Chicken Gyro": {"type":"main course","veg/nonveg":"nonveg"},
 "Fruit Tart": {"type":"dessert","veg/nonveg":"veg"},
 "Stuffed Bell Peppers": {"type":"main course","veg/nonveg":"veg"},
 "Chicken Salad Sandwich": {"type":"main course","veg/nonveg":"nonveg"},
 "Beef Wellington": {"type":"main course","veg/nonveg":"nonveg"},
 "Avocado Toast": {"type":"breakfast","veg/nonveg":"veg"},
 "Chicken Marsala": {"type":"main course","veg/nonveg":"nonveg"},
 "Shrimp Cocktail": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Ratatouille": {"type":"main course","veg/nonveg":"veg"},
 "Chocolate Lava Cake": {"type":"dessert","veg/nonveg":"veg"},
 "Grilled Cheese Sandwich": {"type":"main course","veg/nonveg":"veg"},
 "Beef Carpaccio": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Caprese Panini": {"type":"main course","veg/nonveg":"veg"},
 "Eggplant Rollatini": {"type":"main course","veg/nonveg":"veg"},
 "Tuna Tartare": {"type":"appetizer","veg/nonveg":"nonveg"},
 "Chicken Teriyaki": {"type":"main course","veg/nonveg":"nonveg"},
 "Cheese Fondue": {"type":"appetizer","veg/nonveg":"veg"}
}
#data for places
places={
    "Taj Mahal": {"city": "Agra", "state": "Uttar Pradesh"},
    "Red Fort": {"city": "Delhi", "state": "Delhi"},
    "Qutub Minar": {"city": "Delhi", "state": "Delhi"},
    "Hawa Mahal": {"city": "Jaipur", "state": "Rajasthan"},
    "Amer Fort": {"city": "Jaipur", "state": "Rajasthan"},
    "City Palace, Jaipur": {"city": "Jaipur", "state": "Rajasthan"},
    "Jantar Mantar, Jaipur": {"city": "Jaipur", "state": "Rajasthan"},
    "Mehrangarh Fort": {"city": "Jodhpur", "state": "Rajasthan"},
    "Umaid Bhawan Palace": {"city": "Jodhpur", "state": "Rajasthan"},
    "Jaisalmer Fort": {"city": "Jaisalmer", "state": "Rajasthan"},
    "Gir National Park": {"city": "Junagadh", "state": "Gujarat"},
    "Somnath Temple": {"city": "Somnath", "state": "Gujarat"},
    "Statue of Unity": {"city": "Kevadia", "state": "Gujarat"},
    "Kankaria Lake": {"city": "Ahmedabad", "state": "Gujarat"},
    "Sabarmati Ashram": {"city": "Ahmedabad", "state": "Gujarat"},
    "Golden Temple": {"city": "Amritsar", "state": "Punjab"},
    "Jallianwala Bagh": {"city": "Amritsar", "state": "Punjab"},
    "Wagah Border": {"city": "Amritsar", "state": "Punjab"},
    "Harmandir Sahib": {"city": "Amritsar", "state": "Punjab"},
    "Victoria Memorial": {"city": "Kolkata", "state": "West Bengal"},
    "Howrah Bridge": {"city": "Kolkata", "state": "West Bengal"},
    "Sundarbans National Park": {"city": "South 24 Parganas", "state": "West Bengal"},
    "Fort William, Kolkata": {"city": "Kolkata", "state": "West Bengal"},
    "Sanchi Stupa": {"city": "Sanchi", "state": "Madhya Pradesh"},
    "Khajuraho Temples": {"city": "Khajuraho", "state": "Madhya Pradesh"},
    "Bhimbetka Rock Shelters": {"city": "Bhopal", "state": "Madhya Pradesh"},
    "Gwalior Fort": {"city": "Gwalior", "state": "Madhya Pradesh"},
    "Sanchi Stupa": {"city": "Sanchi", "state": "Madhya Pradesh"},
    "Bhimbetka Rock Shelters": {"city": "Bhopal", "state": "Madhya Pradesh"},
    "Kanha National Park": {"city": "Mandla", "state": "Madhya Pradesh"},
    "Bandhavgarh National Park": {"city": "Umaria", "state": "Madhya Pradesh"},
    "Pachmarhi": {"city": "Pachmarhi", "state": "Madhya Pradesh"},
    "Girnar": {"city": "Junagadh", "state": "Gujarat"},
    "Mahabodhi Temple": {"city": "Bodh Gaya", "state": "Bihar"},
    "Nalanda University": {"city": "Nalanda", "state": "Bihar"},
    "Patna Sahib Gurudwara": {"city": "Patna", "state": "Bihar"},
    "Mahatma Gandhi Setu": {"city": "Patna", "state": "Bihar"},
    "Konark Sun Temple": {"city": "Puri", "state": "Odisha"},
    "Jagannath Temple, Puri": {"city": "Puri", "state": "Odisha"},
    "Chilika Lake": {"city": "Puri", "state": "Odisha"},
    "Lingaraja Temple": {"city": "Bhubaneswar", "state": "Odisha"},
    "Udayagiri and Khandagiri Caves": {"city": "Bhubaneswar", "state": "Odisha"},
    "Biju Patnaik Park": {"city": "Bhubaneswar", "state": "Odisha"},
    "Bihar Sharif": {"city": "Nalanda", "state": "Bihar"},
    "Sri Sri Harmandir Sahib Ji": {"city": "Patna", "state": "Bihar"},
    "Dulhasti Power Plant": {"city": "Chenab Nagar", "state": "Jammu and Kashmir"},
    "Mangla Dam": {"city": "Mirpur", "state": "Azad Kashmir"},
    "Naltar Valley": {"city": "Gilgit", "state": "Gilgit-Baltistan"},
    "Muree": {"city": "Rawalpindi", "state": "Punjab"},
    "Derawar Fort": {"city": "Bahawalpur", "state": "Punjab"},
    "Shalimar Gardens": {"city": "Lahore", "state": "Punjab"},
    "Wazir Khan Mosque": {"city": "Lahore", "state": "Punjab"},
    "Noor Mahal": {"city": "Bahawalpur", "state": "Punjab"},
    "Taxila": {"city": "Rawalpindi", "state": "Punjab"},
    "Shakarparian": {"city": "Islamabad", "state": "Islamabad Capital Territory"},
    "Lok Virsa Museum": {"city": "Islamabad", "state": "Islamabad Capital Territory"},
    "Pakistan Monument": {"city": "Islamabad", "state": "Islamabad Capital Territory"},
    "Faisal Mosque": {"city": "Islamabad", "state": "Islamabad Capital Territory"},
    "Rawal Lake": {"city": "Islamabad", "state": "Islamabad Capital Territory"},
    "Hinglaj Mata Temple": {"city": "Lasbela", "state": "Balochistan"},
    "Mohenjo-daro": {"city": "Larkana", "state": "Sindh"},
    "Port Grand": {"city": "Karachi", "state": "Sindh"},
    "Clifton Beach": {"city": "Karachi", "state": "Sindh"},
    "Karachi Zoo": {"city": "Karachi", "state": "Sindh"},
    "Quaid-e-Azam House": {"city": "Karachi", "state": "Sindh"},
    "Mohatta Palace": {"city": "Karachi", "state": "Sindh"},
    "Frere Hall": {"city": "Karachi", "state": "Sindh"},
    "Empress Market": {"city": "Karachi", "state": "Sindh"},
    "Bagh Ibne Qasim": {"city": "Karachi", "state": "Sindh"},
    "Aga Khan University Hospital": {"city": "Karachi", "state": "Sindh"},
    "Tomb of the Lady": {"city": "Karachi", "state": "Sindh"},
    "Aladin Amusement Park": {"city": "Karachi", "state": "Sindh"},
    "Mazar-e-Quaid": {"city": "Karachi", "state": "Sindh"},
    "Quaid-e-Azam Mausoleum": {"city": "Karachi", "state": "Sindh"},
    "Mazar-e-Quaid": {"city": "Karachi", "state": "Sindh"},
    "Quaid-e-Azam Mausoleum": {"city": "Karachi", "state": "Sindh"},
    "Faqir Island": {"city": "Gwadar", "state": "Balochistan"},
    "Churna Island": {"city": "Karachi", "state": "Sindh"},
    "Shah Jahan Mosque": {"city": "Thatta", "state": "Sindh"},
    "Haleji Lake": {"city": "Thatta", "state": "Sindh"},
    "Thatta": {"city": "Thatta", "state": "Sindh"},
    "Keenjhar Lake": {"city": "Thatta", "state": "Sindh"},
    "Chaukhandi tombs": {"city": "Karachi", "state": "Sindh"},
    "French Beach": {"city": "Karachi", "state": "Sindh"},
    "Hawkes Bay Beach": {"city": "Karachi", "state": "Sindh"},
    "Sandspit Beach": {"city": "Karachi", "state": "Sindh"},
    "Manora": {"city": "Karachi", "state": "Sindh"},
    "Clifton Oyster Rocks": {"city": "Karachi", "state": "Sindh"},
    "Paradise Point": {"city": "Karachi", "state": "Sindh"},
    "Karachi Safari Park": {"city": "Karachi", "state": "Sindh"},
    "Landhi Korangi Zoo": {"city": "Karachi", "state": "Sindh"},
    "Tomb of Chittano": {"city": "Karachi", "state": "Sindh"},
    "Tomb of Talpur": {"city": "Karachi", "state": "Sindh"},
    "Churna Island": {"city": "Karachi", "state": "Sindh"},
    "Astola Island": {"city": "Pasni", "state": "Balochistan"},
    "Clifton Beach": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Cape Monze": {"city": "Karachi", "state": "Sindh"},
    "Cape Mount": {"city": "Karachi", "state": "Sindh"},
    "Cape Nozha": {"city": "Karachi", "state": "Sindh"},
    "Cape Sui": {"city": "Karachi", "state": "Sindh"},
    "Ajanta Caves": {"city": "Aurangabad", "state": "Maharashtra"},
    "Ellora Caves": {"city": "Aurangabad", "state": "Maharashtra"},
    "Elephanta Caves": {"city": "Mumbai", "state": "Maharashtra"},
    "Gateway of India": {"city": "Mumbai", "state": "Maharashtra"},
    "Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (formerly Prince of Wales Museum)": {"city": "Mumbai", "state": "Maharashtra"},
    "Marine Drive": {"city": "Mumbai", "state": "Maharashtra"},
    "Hanging Gardens": {"city": "Mumbai", "state": "Maharashtra"},
    "Siddhivinayak Temple": {"city": "Mumbai", "state": "Maharashtra"},
    "Mysore Palace": {"city": "Mysore", "state": "Karnataka"},
    "Hampi": {"city": "Bellary", "state": "Karnataka"},
    "Gol Gumbaz": {"city": "Bijapur", "state": "Karnataka"},
    "Chamundi Hills": {"city": "Mysore", "state": "Karnataka"},
    "Brindavan Gardens": {"city": "Mysore", "state": "Karnataka"},
    "Ranganathaswamy Temple": {"city": "Srirangapatna", "state": "Karnataka"},
    "Jog Falls": {"city": "Shimoga", "state": "Karnataka"},
    "Kudremukh National Park": {"city": "Chikkamagaluru", "state": "Karnataka"},
    "Bannerghatta National Park": {"city": "Bangalore", "state": "Karnataka"},
    "Nandi Hills": {"city": "Chikkaballapur", "state": "Karnataka"},
    "Kodagu (Coorg)": {"city": "Madikeri", "state": "Karnataka"},
    "Auroville": {"city": "Puducherry", "state": "Puducherry"},
    "Puducherry Beach": {"city": "Puducherry", "state": "Puducherry"},
    "Aurobindo Ashram": {"city": "Puducherry", "state": "Puducherry"},
    "Paradise Beach": {"city": "Puducherry", "state": "Puducherry"},
    "Sri Aurobindo Hand Made Paper Factory": {"city": "Puducherry", "state": "Puducherry"},
    "Karaikal Beach": {"city": "Karaikal", "state": "Puducherry"},
    "Chunnambar Boat House": {"city": "Puducherry", "state": "Puducherry"},
    "The Promenade": {"city": "Puducherry", "state": "Puducherry"},
    "Botanical Garden": {"city": "Puducherry", "state": "Puducherry"},
    "Gingee Fort": {"city": "Villupuram", "state": "Tamil Nadu"},
    "Puducherry Museum": {"city": "Puducherry", "state": "Puducherry"},
    "Raj Niwas": {"city": "Puducherry", "state": "Puducherry"},
    "Basilica of the Sacred Heart of Jesus": {"city": "Puducherry", "state": "Puducherry"},
    "Rajiv Gandhi Water Sports Complex": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Cellular Jail": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Radhanagar Beach": {"city": "Havelock Island", "state": "Andaman and Nicobar Islands"},
    "Ross Island": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Barren Island": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Viper Island": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Elephant Beach": {"city": "Havelock Island", "state": "Andaman and Nicobar Islands"},
    "Laxmanpur Beach": {"city": "Neil Island", "state": "Andaman and Nicobar Islands"},
    "Neil Island": {"city": "Neil Island", "state": "Andaman and Nicobar Islands"},
    "Mahatma Gandhi Marine National Park": {"city": "Wandoor", "state": "Andaman and Nicobar Islands"},
    "Corbyn's Cove Beach": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Samudrika Marine Museum": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Mount Harriet National Park": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Chidiya Tapu": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Cinque Island": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Baratang Island": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Havelock Island": {"city": "Havelock Island", "state": "Andaman and Nicobar Islands"},
    "Ross and Smith Islands": {"city": "Diglipur", "state": "Andaman and Nicobar Islands"},
    "Diglipur": {"city": "Diglipur", "state": "Andaman and Nicobar Islands"},
    "North Bay Island": {"city": "Port Blair", "state": "Andaman and Nicobar Islands"},
    "Wandoor Beach": {"city": "Wandoor", "state": "Andaman and Nicobar Islands"},
    "Little Andaman Island": {"city": "Little Andaman", "state": "Andaman and Nicobar Islands"},
    "Saddle Peak": {"city": "Diglipur", "state": "Andaman and Nicobar Islands"},
    "Mayabunder": {"city": "Mayabunder", "state": "Andaman and Nicobar Islands"},
    "Mud Volcanoes": {"city": "Baratang Island", "state": "Andaman and Nicobar Islands"},
    "Red Skin Island": {"city": "Havelock Island", "state": "Andaman and Nicobar Islands"},
    "Lalaji Bay Beach": {"city": "Long Island", "state": "Andaman and Nicobar Islands"},
    "Charminar": {"city": "Hyderabad", "state": "Telangana"},
    "Golconda Fort": {"city": "Hyderabad", "state": "Telangana"},
    "Salar Jung Museum": {"city": "Hyderabad", "state": "Telangana"},
    "Ramoji Film City": {"city": "Hyderabad", "state": "Telangana"},
    "Mecca Masjid": {"city": "Hyderabad", "state": "Telangana"},
    "Qutb Shahi Tombs": {"city": "Hyderabad", "state": "Telangana"},
    "Birla Mandir, Hyderabad": {"city": "Hyderabad", "state": "Telangana"},
    "Nehru Zoological Park": {"city": "Hyderabad", "state": "Telangana"},
    "KBR National Park": {"city": "Hyderabad", "state": "Telangana"},
    "Rajiv Gandhi International Cricket Stadium": {"city": "Hyderabad", "state": "Telangana"},
    "Kailasagiri": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "Borra Caves": {"city": "Araku Valley", "state": "Andhra Pradesh"},
    "Araku Valley": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "Indira Gandhi Zoological Park": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "INS Kursura Submarine Museum": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "Rishikonda Beach": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "Yarada Beach": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "VUDA Park": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "Sri Venkateswara Temple, Tirumala": {"city": "Tirupati", "state": "Andhra Pradesh"},
    "Kanaka Durga Temple": {"city": "Vijayawada", "state": "Andhra Pradesh"},
    "Undavalli Caves": {"city": "Vijayawada", "state": "Andhra Pradesh"},
    "Bhavani Island": {"city": "Vijayawada", "state": "Andhra Pradesh"},
    "Kondapalli Fort": {"city": "Vijayawada", "state": "Andhra Pradesh"},
    "Mangalagiri Temple": {"city": "Vijayawada", "state": "Andhra Pradesh"},
    "Prakasam Barrage": {"city": "Vijayawada", "state": "Andhra Pradesh"},
    "Kolleru Lake": {"city": "Eluru", "state": "Andhra Pradesh"},
    "Nelapattu Bird Sanctuary": {"city": "Nellore", "state": "Andhra Pradesh"},
    "Belum Caves": {"city": "Kurnool", "state": "Andhra Pradesh"},
    "Gandikota": {"city": "Kadapa", "state": "Andhra Pradesh"},
    "Pulicat Lake": {"city": "Nellore", "state": "Andhra Pradesh"},
    "Talakona Waterfall": {"city": "Chittoor", "state": "Andhra Pradesh"},
    "Ahobilam Temple": {"city": "Nandyal", "state": "Andhra Pradesh"},
    "Uppalapadu Bird Sanctuary": {"city": "Guntur", "state": "Andhra Pradesh"},
    "Horsley Hills": {"city": "Chittoor", "state": "Andhra Pradesh"},
    "Ethipothala Falls": {"city": "Guntur", "state": "Andhra Pradesh"},
    "Kondaveedu Fort": {"city": "Guntur", "state": "Andhra Pradesh"},
    "Nagarjunakonda": {"city": "Guntur", "state": "Andhra Pradesh"},
    "Kanipakam Vinayaka Temple": {"city": "Chittoor", "state": "Andhra Pradesh"},
    "Kondapalli Toys Village": {"city": "Vijayawada", "state": "Andhra Pradesh"},
    "Suryalanka Beach": {"city": "Bapatla", "state": "Andhra Pradesh"},
    "Mypadu Beach": {"city": "Nellore", "state": "Andhra Pradesh"},
    "Kuchipudi Village": {"city": "Krishna", "state": "Andhra Pradesh"},
    "Kolleru Lake Bird Sanctuary": {"city": "Eluru", "state": "Andhra Pradesh"},
    "Papikondalu": {"city": "Rajahmundry", "state": "Andhra Pradesh"},
    "Pavuralakonda": {"city": "Visakhapatnam", "state": "Andhra Pradesh"},
    "Vikramasimhapuri": {"city": "Nellore", "state": "Andhra Pradesh"},
    "Udayagiri and Khandagiri Caves": {"city": "Bhubaneswar", "state": "Odisha"},
}


def recommend_based_on_preference(choice):
    if choice=='dramas':
      def recommend_dramas(korean_dramas, chinese_dramas):
          genre = input("Enter the genre (romance, fantasy, historical,mystery,action,crime etc.): ").lower()
          recommended_korean = {}
          recommended_chinese = {}
          for drama, details in korean_dramas.items():
              if details["genre"].lower() == genre :
                recommended_korean[drama] = details
          for drama, details in chinese_dramas.items():
             if details["genre"].lower() == genre :
               recommended_chinese[drama] = details

          return recommended_korean, recommended_chinese
      recommended_korean, recommended_chinese = recommend_dramas(korean_dramas, chinese_dramas)
      print("Recommended Korean Dramas:")
      print(recommended_korean)
      print("\nRecommended Chinese Dramas:")
      print(recommended_chinese)


    elif choice == "food":
         def recommend_food(food_items, food_type, veg_nonveg):
             recommended_food = []
             for food, details in food_items.items():
                 if details["type"] == food_type and details["veg/nonveg"] == veg_nonveg:
                    recommended_food.append(food)
             return recommended_food

         food_type = input("Enter the type of food (e.g., dessert, main course, appetizer, beverage,side dish,soup etc.): ")
         veg_nonveg = input("Enter 'veg' or 'nonveg' to specify vegetarian or non-vegetarian preference: ")

         recommended = recommend_food(food_items, food_type, veg_nonveg)
         if recommended:
            print("Recommended", food_type, "options (", veg_nonveg, "):")
            for food in recommended:
               print("-", food)
         else:
             print("Sorry, no matching food items found.")
    elif choice=="place":
      def recommend_places_by_state(state):
          recommended_places = []
          for place, location in places.items():
              if location["state"].lower() == state.lower():
                 recommended_places.append(place)
          return recommended_places


      user_input_state = input("Enter the state to get recommended places: ")
      recommended_places = recommend_places_by_state(user_input_state)
      if recommended_places:
         print(f"Recommended places to visit in {user_input_state}:")
         for place in recommended_places:
             print(place)
      else:
           print("No places found for the given state.")



    else:
        print("Invalid choice! Please choose either 'dramas' or 'food'.")
user_choice = input("What would you like to get recommendations for? Type 'dramas' or 'food' or 'place': ").lower()
recommend_based_on_preference(user_choice)







